modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/Hostile-Neural-Compat/issues"

[[mods]]
modId="hostile_neural_compat"
version="1.16.5-1.0.2"
displayName="Hostile Neural Compat"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hostile_neural_compat"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
Add Mod Compat to Hostile Neural Networks
'''

[[dependencies.hostile_neural_compat]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hostile_neural_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"